server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnesstrackingapp
      database: fitnesstrackingapp

  rabbitmq:
    host: localhost
    port: 5672
    username: _shubhammeshram
    password: 123456



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
